### ISSUE TITLE
Can't add two attributes with different value

### ISSUE THREAD

**Issue by KickerTom** [stuvusIT/slapd-config#21]
For auditlog overlay, the [recommended ldif](https://linux.die.net/man/5/slapo-auditlog) is:
```
dn: olcOverlay=auditlog,olcDatabase={1}hdb,cn=config
changetype: add
objectClass: olcOverlayConfig
objectClass: olcAuditLogConfig
olcOverlay: auditlog
olcAuditlogFile: /tmp/auditlog.ldif
```
However, when I specify objectClass twice in the playbook, the slapd-config role creates the first one, and then tries to replace it with the second one (and failing). I tried using list/array, but does not seem to help.
Is there any way around? I had a look at the slapd-overlay-attribute-upsert script, and it does not seem to be prepared for repeating arguments, but I may be missing something...

**Comment by haslersn** [comment]
We archive this repository.
