### ISSUE TITLE
Create MDB Overlays fails if monitoring is disabled

### ISSUE THREAD

**Issue by antonu17** [stuvusIT/slapd-config#22]
Hi @dasJ,

thanks for an amazing role! I found a small issue with olcDatabases creation. When I disable monitoring via `slapd_enable_monitor: false` monitor-create.yml is skipped.

We have `olcDatabase: {1}monitor` hardcoded into `slapd-create-monitor`, and `olcDatabase: {2}mdb` hardcoded into `slapd-mdb-create`. In case of skipping `slapd-create-monitor` openldap gives `{1}` to oclDatabase mdb, even though it is added like `olcDatabase: {2}mdb` it becomes `olcDatabase: {1}mdb`.

When it comes to creating overlays `mdb-overlay-create.yml` calls `/usr/local/bin/slapd-create-overlay` with `"olcDatabase={2}mdb,cn=config"` argument (hardcoded) and at this point role fails because it can't find `{2}`.

**Comment by haslersn** [comment]
We archive this repository.
